{
  "frontend": {
    "impl": "External",
    "clock_ratio": 1
  },
  "memory_system": {
    "impl": "GenericDRAM",
    "clock_ratio": 1,
    "channel_mapper": {
      "impl": "PassThroughChannelMapper"
    },
    "controllers": [{
      "impl": "HBM",
      "wr_low_watermark": 0.2,
      "wr_high_watermark": 0.8,
      "read_buffer_size": 64,
      "write_buffer_size": 64,
      "priority_buffer_size": 1568,
      "scheduler": {
        "impl": "FRFCFS"
      },
      "refresh_manager": {
        "impl": "AllBank",
        "scope": "PseudoChannel"
      },
      "row_policy": {
        "impl": "Open"
      },
      "addr_mapper": {
        "impl": "RoBaRaCoCh"
      },
      "dram": {
        "impl": "HBM2",
        "org": {
          "dq": 64,
          "count": [1, 2, 4, 4, 65536, 32]
        },
        "timing": [1880, 2, 13, 13, 11, 13, 31, 44, 15, 5, 5, 2, 4, 4, 4, 6, 8, 15, 329, 151, 8, 3666, 115, 1064],
        "channel_width": 64,
        "read_latency": 15,
        "timing_constraints": [[0, [0], [0, 1, 2, 7, 8], 2], [1, [3, 5], [3, 5], 2], [1, [4, 6], [4, 6], 2], [1, [3, 5], [3, 5], 2], [1, [4, 6], [4, 6], 2], [1, [3, 5], [4, 6], 12], [1, [4, 6], [3, 5], 13], [1, [3], [2], 5], [1, [4], [2], 22], [1, [0], [0], 4], [1, [0], [0], 15, 4], [1, [0], [2], 32], [1, [2], [0], 12], [1, [0], [7], 45], [1, [1, 2], [7], 13], [1, [5], [7], 18], [1, [6], [7], 35], [1, [7], [0], 328], [1, [7], [2], 329], [1, [8], [0], 7], [1, [0], [8], 5], [2, [3, 5], [3, 5], 4], [2, [4, 6], [4, 6], 4], [2, [4, 6], [3, 5], 15], [2, [0], [0], 4], [3, [0], [0], 44], [3, [0], [3, 5], 14], [3, [0], [4, 6], 12], [3, [0], [1], 32], [3, [1], [0], 12], [3, [3], [1], 5], [3, [4], [1], 22], [3, [5], [0], 17], [3, [6], [0], 34], [3, [8], [0], 150], [3, [0], [8], 45], [3, [1], [8], 13]]
      }
    }]
  }
}