core_type:
- stonne
stonne_config_path: /workspace/PyTorchSim/TOGSim/extern/stonneCore/tests/sparseflex_op_128mses_128_bw.cfg
num_cores: 1
core_freq_mhz: 700
core_stats_print_period_cycles: 10000
num_stonne_per_core: 1
num_stonne_port: 8

dram_type: ramulator2
dram_freq_mhz: 700
dram_channels: 8
dram_stats_print_period_cycles: 10000
ramulator_config_path: ../configs/ramulator2_configs/HBM2_TPUv2.yaml

icnt_type: simple
icnt_latency_cycles: 10
icnt_freq_mhz: 700
icnt_injection_ports_per_core: 8
